### ISSUE TITLE
Content writing for minting website

### ISSUE THREAD

**Issue by rasmuscnielsen** [Developer-DAO/ukraine-donation-nft#13]
We need write up some text for

- NFT description
- FAQ incl roadmap
- Overall proof reading of text on website
- We need a new meta data title/summary for the site. See also #14 
- Also what name should we use for the NFT contract? It's currently `PXLDEV-UKRAINE`. See #22 

Will post link to staging website soon so work can start on this

**Comment by briangershon** [comment]
Here's link to staging site: https://ukraine-staging.developerdao.com
