### ISSUE TITLE
Change social preview

### ISSUE THREAD

**Issue by rasmuscnielsen** [Developer-DAO/ukraine-donation-nft#14]
## Website

- [ ] Meta description for website
- [ ] OG image for website which lives at https://ukraine-staging.developerdao.com/meta.png
- [ ] Favicon for website

## OpenSea Collection Image

- [ ] Image for OpenSea collection. Collection is set to pull image from https://ukraine-staging.developerdao.com/meta.png

**Comment by briangershon** [comment]
Maybe @eknobl can help with social preview image and maybe favicon?

Then @rasmuscnielsen or another one of us can update the meta description. See also #13
