### ISSUE TITLE
Contract is not customizable in OpenSea

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/ukraine-donation-nft#28]
## Problem

We're not able to edit the collection on OpenSea based on our contract.

Start of conversation in Discord: https://discord.com/channels/883478451850473483/884980325653049367/955994162686222426

## Solutions

Contracts need to be "Ownable" + have Contract metadata: https://support.opensea.io/hc/en-us/articles/4403934341907-How-do-I-import-my-contract-automatically-

I wonder if our roles-based system is causing the problem? (by not supporting Ownable)

### Potential Solution 1

Is it possible to change contract to support both Ownable along with AccessControlEnumerable?

### Potential Solution 2

Instead of supporting Ownable, maybe adding the Contract metadata (plus ContractURI() in contract) with all the settings will be enough. So we wouldn't be able to customize in OpenSea UI, but maybe don't need to.

**Comment by briangershon** [comment]
I'll work on adding the contract metadata file on IPFS and adding `ContractURI()` to contract.

**Comment by itstargetconfirmed** [comment]
@briangershon OpenSea looks for a method `owner()` that returns the owner of the contract. I can implement this method and return the first administrator in the contract. 

This would mean only the first administrator can customize the settings on OpenSea. What are your thoughts?

**Comment by briangershon** [comment]
Thanks @itstargetconfirmed I think having only the contract owner be able to edit OpenSea collection metadata is ok.

**Comment by briangershon** [comment]
The new contract metadata is there now. This was completed in PR #30
