### ISSUE TITLE
Finish Testing and Deploy Production Contract

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/ukraine-donation-nft#42]
## Test Contracts and Collections

- [Mumbai contract for staging](https://mumbai.polygonscan.com/address/0x2131EB7133688CC88139e9fb60C6Ba646Fdf033d) and [OpenSea collection](https://testnets.opensea.io/collection/developer-dao-for-ukraine)
- [Rinkeby contract](https://rinkeby.etherscan.io/address/0x49876dF684D5bC682Aa17729A5265a2717726C33) and [OpenSea collection](https://testnets.opensea.io/collection/developer-dao-for-ukraine-v4).

## Finish testing on Mumbai and Rinkeby

- [x] Rinkeby: Finish testing Royalties
- [x] Mumbai: Finish testing successful Mint and Payment. Manually run through the primary flow on our Mumbai contract, setting everything to my fresh test wallet, including:
  - Set Admin Role
  - Set Wallet address (recipient of donations)
  - Set WITHDRAW_ROLE
  - Actually withdraw
- [x] Mumbai: Review OpenSea meta data
- [x] Mumbai: Update contract roles
- [x] Mumbai: Test money transfer

## Production Deploy

- [x] Deploy to Polygon mainnet
- [x] Update contract roles
- [x] Test mint
- [x] Test money transfer

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk
