### ISSUE TITLE
Post Launch Publicity Ideas

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/ukraine-donation-nft#48]
- Record a short message from say 5 DevDAO people explaining importance of project and why Developer DAO is supporting.
- Video dev'n'tell on Youtube or Friday dev'n'tell explaining technical aspects of site. Either as a prelaunch or "looking back (post launch)". Possible content: contract testing, security issues

**Comment by briangershon** [comment]
@itstargetconfirmed interested in writing blog post about EIP-2981 (Royalties).

**Comment by ornaeric** [comment]
https://twitter.com/U24_gov_ua/status/1628751794762383361?t=91CjGFOyOg0clIShbcoAYQ&s=09

https://twitter.com/KremlinTrolls/status/1628901587019091968?t=AkZyztsT_Pq_qnVRYpQO1w&s=09

https://twitter.com/U24_gov_ua/status/1628751794762383361?t=91CjGFOyOg0clIShbcoAYQ&s=09

What publicity, the ones that's a scam and stealing the donation? Even the Ukraine Government said they have nothing to do with DAO.

**Comment by briangershon** [comment]
Closing issue prior to archiving repository.
